DEBUG ON;

OPEN QROSS;
PRINT  '''@KEEPER_HTTP_ADDRESS:@KEEPER_HTTP_PORT/task/instant1/#{jobId}''';
REQUEST JSON API '''@KEEPER_HTTP_ADDRESS:@KEEPER_HTTP_PORT/task/instant1/#{jobId}''' METHOD 'PUT';
PARSE "/" AS ROW;