DEBUG ON;

OPEN QROSS;


VAR $task := SELECT id, status FROM qross_tasks WHERE id>0 LIMIT 0 -> FIRST ROW { };

IF $task IS EMPTY THEN
    PRINT 'EMPTY';
END IF;

IF $task IS NULL THEN
    PRINT 'NULL';
END IF;

IF $task IS UNDEFINED THEN
    PRINT 'UNDEFINED';
END IF;